# =====================================================
# ARPES Fine-Tuning Configuration v1.0
# Created: 2025-04-14
#
# Training params:
# - 128x128 patches
# - Batch size 16
# - 100k iterations
# - Both rotation and flip augmentations
# - Standard noise parameters
# =====================================================



# general settings
name: finetune_RealESRGAN_ARPES_x4plus_0
model_type: RealESRGANModel
scale: 4
num_gpu: auto  # Will detect available GPUs on Mac
manual_seed: 0

# USM the ground-truth (sharpening)
l1_gt_usm: True
percep_gt_usm: True
gan_gt_usm: False

# The first degradation process - adjusted for Mac performance
resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
resize_range: [0.15, 1.5]
gaussian_noise_prob: 0.5
noise_range: [1, 30]
poisson_scale_range: [0.05, 3]
gray_noise_prob: 0.4
jpeg_range: [30, 95]

# The second degradation process
second_blur_prob: 0.8
resize_prob2: [0.3, 0.4, 0.3]
resize_range2: [0.3, 1.2]
gaussian_noise_prob2: 0.5
noise_range2: [1, 25]
poisson_scale_range2: [0.05, 2.5]
gray_noise_prob2: 0.4
jpeg_range2: [30, 95]

# Further reduced patch size for Mac
gt_size: 96  # Reduced from 128 to 96 for Mac
queue_size: 120  # Reduced from 180 to 120 for Mac

# dataset settings
datasets:
  train:
    name: ARPES
    type: RealESRGANDataset
    dataroot_gt: datasets/ARPES_data/training_images
    meta_info: datasets/ARPES_data/meta_info/meta_info_ARPES.txt
    io_backend:
      type: disk

    # Kernel settings for degradation simulation - slightly simplified for Mac
    blur_kernel_size: 21
    kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob: 0.1
    blur_sigma: [0.2, 3]
    betag_range: [0.5, 4]
    betap_range: [1, 2]

    blur_kernel_size2: 21
    kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob2: 0.1
    blur_sigma2: [0.2, 1.5]
    betag_range2: [0.5, 4]
    betap_range2: [1, 2]

    final_sinc_prob: 0.8

    # Modified patch size to match the new gt_size and Mac capabilities
    gt_size: 96  # Reduced from 128 to 96 for Mac
    use_hflip: True
    use_rot: True

    # data loader - optimized for Mac
    use_shuffle: true
    num_worker_per_gpu: 2  # Reduced from 4 to 2 for Mac
    batch_size_per_gpu: 4  # Reduced from 16 to 4 for Mac
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

# network settings - slightly simplified for Mac
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 16  # Reduced from 23 to 16 for Mac
  num_grow_ch: 32

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 48  # Reduced from 64 to 48 for Mac
  skip_connection: True

# path settings
path:
  # Pre-trained models
  pretrain_network_g: experiments/pretrained_models/RealESRNet_x4plus.pth
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: experiments/pretrained_models/RealESRGAN_x4plus_netD.pth
  param_key_d: params
  strict_load_d: true
  resume_state: ~

# training settings - optimized for Mac
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 5e-5  # Further reduced for Mac stability
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 5e-5  # Further reduced for Mac stability
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [25000, 50000]  # Adjusted for shorter training
    gamma: 0.5

  total_iter: 50000  # Further reduced for Mac training
  warmup_iter: -1

  # losses (unchanged)
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  # perceptual loss
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    style_weight: 0
    range_norm: false
    criterion: l1
  # gan loss
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

  net_d_iters: 1
  net_d_init_iters: 0

# logging settings - more frequent checkpoints for Mac (in case of crashes)
logger:
  print_freq: 50  # Reduced from 100 to 50 for more frequent updates
  save_checkpoint_freq: !!float 2e3  # Save more frequently on Mac
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500